### ISSUE TITLE
Toggle menu covers the sketch

### ISSUE THREAD

**Issue by thedanheller** [chiunhau/p5-manager#12]
If you have a small canvas or if your sketch happens in the top left corner, the toggle menu covers a significant part of the sketch.

I think it would be good to make it smaller, or maybe having a margin on the body so the canvas doesn't reach that part.

**Comment by chiunhau** [comment]
@daniloprates Yes, I've been working on this. And this would be released along with #11.

**Comment by thedanheller** [comment]
that's great!
