### ISSUE TITLE
Can p5-manager be configured to start with other servers (e.g. lite-server, http-server)?

### ISSUE THREAD

**Issue by criticalhits** [chiunhau/p5-manager#18]
For example, I just set up my local development environment yesterday with p5 and lite-server, because I found it was really handy to edit files, and the browser automatically refresh when you save the file (e.g. the sketch).

I'm new to web development - thanks for your patience with me!

**Comment by chiunhau** [comment]
Sorry @criticalhits, as I know, I don't think p5-manager can work with other server, because p5-manager itself is already an Express server. 
However, I'm working on auto-reloading and it would be introduced in the future release. (I hope so 👍 )
