### ISSUE TITLE
Live Reload

### ISSUE THREAD

**Issue by ianfitzpatrick** [chiunhau/p5-manager#19]
Hi There, 

Thanks for making this.

Was wondering if there would be a way to add live reload, I believe this is the same as opening a node express server with options `--open --hot`.

I see that the GUI you built for this is in Vue, so basically what I'm asking for is the same thing that vue-cli + vue-loader gives you, the ability to reload the page on file save w/ es6, without the need to manually reload the browser page.

Any idea if that would be possible?

**Comment by chiunhau** [comment]
Yes this is exactly what I'm going to do 👍

**Comment by ianfitzpatrick** [comment]
Oh hey, sorry no longer any need to do this on my behalf at least.

I ended up just using ES6 in browser without babel. It works except for module imports, which is okay. I'm not distributing my sketches so don't need to worry about ES5.

This way errors don't get swallowed, and I can step through code easier without having to set up source mappings. I just use a `python -m SimpleHTTPServer` as my web server, and a bash script to create new sketches.

This method gives me live reload in chrome too =\

Sorry!

**Comment by chiunhau** [comment]
@ianfitzpatrick Okay but I'll still work on this because I do need an environment for quick developing though 😸

**Comment by xupisco** [comment]
Hi there, any news on live reload option?  
Tks

**Comment by chiunhau** [comment]
Now support in 0.4.0
