### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by tioirawan** [chiunhau/p5-manager#22]
i got this error

` $ npm install -g p5-manager

npm WARN deprecated babel-preset-es2015@6.24.1: We're super 😸  excited that you're trying to use ES2015 syntax, but instead of continuing yearly presets 😭 , we recommend using babel-preset-env: npm install babel-preset-env. preset-env without options will compile ES2015+ down to ES5. And by targeting specific browsers, Babel can do less work and you can ship native ES2015+ to users 😎 ! Also, we are in the process of releasing v7, so give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and test it! Thanks so much for using Babel 🙏 , please give us a follow @babeljs for updates, join slack.babeljs.io for discussion and help support at opencollective.com/babel

npm ERR! Unexpected end of input at 1:25655

npm ERR! x","karma-firefox-launcher":"0.1.x","karma-opera-launcher":"0.1.x","p

npm ERR! `

**Comment by chiunhau** [comment]
Hi @Indmind thank you for reporting this.
I think it's not p5-manager's issue, but something related to your local npm or node. I just found some similar issues on other package. Try running this `npm cache clean --force` and then `npm install -g p5-manager` again! 

Please let me know if you solve it 🙇

**Comment by tioirawan** [comment]
now i'ts work, yesterday i tried `npm cache clean --force` too, but it doesn't work, now i tried it again and it's work! thanks

**Comment by chiunhau** [comment]
OK! Thank you.
