### ISSUE TITLE
.p5rc not created

### ISSUE THREAD

**Issue by nlooije** [chiunhau/p5-manager#23]
While trying out the GUI i noticed none of my projects were loaded in the side menu.
The console log showed: `Error: ENOENT: no such file or directory, open '$PATH_TO_MYCOLLECTION.p5rc'`
On inspection no file `.p5rc` was found in the directory. 
I solved the problem by manually creating the file and adding the projects:

.p5rc example:
```
{
    "collectionName": "myp5js",
    "projects": [
        "project_1", 
        "project_2"
    ]
}
```

**Comment by chiunhau** [comment]
@nlooije Hi thanks for reporting. Are you running on Windows?

**Comment by nlooije** [comment]
Hi, yes W10. I now see that the same issue was closed yesterday. Should have spend more time searching. Sorry.

**Comment by chiunhau** [comment]
@nlooije Actually I'm not sure if its my package's problem or not. I haven't test it on a Windows machine yet. Make sure you are running `p5 server` in a collection directory (there should be a .p5rc )

**Comment by nlooije** [comment]
As it turns out i am just really bad at reading instructions, i have created a collection folder manually. If i run `p5 new test_collection` and create a new project `p5 g test_project` everything works as expected. Even on W10. My mistake.

**Comment by chiunhau** [comment]
@nlooije Okay!! （Maybe it's because of my poor English 🙇 ）Maybe you can help me improve the instruction 😃

**Comment by nlooije** [comment]
It is not your English, it is literally the first step of the installation, i am just bad at reading and following instruction :). Maybe to make it explicit you could add at the end of the Step 1 that with the `new` command a configuration file `.p5rc` is generated with a list of the projects used in the GUI.
