### ISSUE TITLE
Keyboard events appear to not be firing in GUI mode

### ISSUE THREAD

**Issue by chris-erxnieves** [chiunhau/p5-manager#32]
Thank you so much for doing this project! I'm just getting into using p5.js and this project has been an absolute godsend.

It appears that keyboard events aren't firing in GUI mode only. It looks like mouse events like `mouseMoved` fire correctly. I wonder if the keyboard events are just failing to be passed along into the iframe.

**Comment by chiunhau** [comment]
@chris-erxleben Hi thanks for reporting this. Yes I think it's due to the iframe. And I found that it will work if I click the iframe area first and start testing keyboard. Interesting 🤣

**Comment by chiunhau** [comment]
Okay I fixed it!! See 0.4.1
