### ISSUE TITLE
Is it possible to generate sketch without a collection

### ISSUE THREAD

**Issue by adalberth** [chiunhau/p5-manager#9]
If I want my sketches to have there own lib files with different versions of p5. Is it possible to just generate a sketch with the libs included in the same folder, instead of create a collection that shares the same libs?

**Comment by chiunhau** [comment]
Hi @adalberth thanks for the suggestion. I think this command is quite necessary, but would be a very big change that need to be well planned. I'll start working on this feature in few days, and any help would be appreciated!!!  ♪( ´▽｀)

**Comment by chiunhau** [comment]
Hi @adalberth , now able to use `p5 generate PROJECT_NAME --bundle` or `p5 g PROJECT_NAME -b`, to generate standalone projects, anywhere.
